#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.10 2014/05/05 22:25:56 brownd Exp $
# $Author: brownd $
# $Date: 2014/05/05 22:25:56 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [
] )

helper.make_plugins( [
    mainlib,
    ] )


helper.make_dict_and_map( [
    mainlib,
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
